import { CatalogCategory, MaterialType } from '../types/furniture';

export const CATALOG: CatalogCategory[] = [
  {
    id: 'kitchen',
    label: 'Cozinha & Gabinetes',
    icon: 'CookingPot',
    items: [
      { id: 'cab-base-2', name: 'Balcão Base 2 Portas', w: 0.8, d: 0.6, h: 0.85, by: 0, pr: 'base', modelUrl: '/models/kitchenCabinet.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'cab-base-drawers', name: 'Balcão com Gaveteiro', w: 0.8, d: 0.6, h: 0.85, by: 0, pr: 'base', modelUrl: '/models/kitchenCabinetDrawer.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'cab-corner-in', name: 'Gabinete de Canto Interno', w: 0.9, d: 0.9, h: 0.85, by: 0, pr: 'base', modelUrl: '/models/kitchenCabinetCornerInner.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'cab-corner-round', name: 'Gabinete Terminal Curvo', w: 0.6, d: 0.6, h: 0.85, by: 0, pr: 'base', modelUrl: '/models/kitchenCabinetCornerRound.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'cab-wall-single', name: 'Armário Aéreo 1 Porta', w: 0.6, d: 0.35, h: 0.7, by: 1.5, pr: 'wall', modelUrl: '/models/kitchenCabinetUpper.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'cab-wall-double', name: 'Armário Aéreo 2 Portas', w: 1.0, d: 0.35, h: 0.7, by: 1.5, pr: 'wall', modelUrl: '/models/kitchenCabinetUpperDouble.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'cab-wall-corner', name: 'Armário Aéreo de Canto', w: 0.65, d: 0.65, h: 0.7, by: 1.5, pr: 'wall', modelUrl: '/models/kitchenCabinetUpperCorner.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'cab-wall-low', name: 'Armário Aéreo Basculante', w: 0.8, d: 0.35, h: 0.4, by: 1.7, pr: 'wall', modelUrl: '/models/kitchenCabinetUpperLow.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'kitchen-sink', name: 'Pia Inox com Bancada', w: 0.9, d: 0.6, h: 0.85, by: 0, pr: 'base', modelUrl: '/models/kitchenSink.glb', dm: { t: 'metal', c: '#d4d4d8' } },
      { id: 'kitchen-bar', name: 'Bancada Gourmet / Ilha', w: 1.4, d: 0.7, h: 0.9, by: 0, pr: 'base', modelUrl: '/models/kitchenBar.glb', dm: { t: 'wood', c: '#2c2c2c' } },
      { id: 'kitchen-bar-end', name: 'Terminal de Bancada Bar', w: 0.7, d: 0.7, h: 0.9, by: 0, pr: 'base', modelUrl: '/models/kitchenBarEnd.glb', dm: { t: 'wood', c: '#2c2c2c' } },
    ],
  },
  {
    id: 'appliances',
    label: 'Eletrodomésticos',
    icon: 'Zap',
    items: [
      { id: 'fridge-large', name: 'Geladeira Duplex Inox', w: 0.85, d: 0.8, h: 1.9, by: 0, pr: 'fr', modelUrl: '/models/kitchenFridgeLarge.glb', dm: { t: 'metal', c: '#e4e4e7' } },
      { id: 'fridge-builtin', name: 'Geladeira Embutida', w: 0.75, d: 0.75, h: 1.85, by: 0, pr: 'fr', modelUrl: '/models/kitchenFridgeBuiltIn.glb', dm: { t: 'metal', c: '#d4d4d8' } },
      { id: 'fridge-small', name: 'Frigobar / Geladeira Compacta', w: 0.55, d: 0.6, h: 0.9, by: 0, pr: 'fr', modelUrl: '/models/kitchenFridgeSmall.glb', dm: { t: 'metal', c: '#ffffff' } },
      { id: 'stove-gas', name: 'Fogão 4 Bocas com Forno', w: 0.6, d: 0.65, h: 0.9, by: 0, pr: 'fr', modelUrl: '/models/kitchenStove.glb', dm: { t: 'metal', c: '#18181b' } },
      { id: 'stove-electric', name: 'Cooktop Elétrico & Forno', w: 0.6, d: 0.6, h: 0.85, by: 0, pr: 'base', modelUrl: '/models/kitchenStoveElectric.glb', dm: { t: 'metal', c: '#27272a' } },
      { id: 'microwave', name: 'Forno Micro-ondas', w: 0.55, d: 0.4, h: 0.35, by: 1.0, pr: 'wall', modelUrl: '/models/kitchenMicrowave.glb', dm: { t: 'metal', c: '#27272a' } },
      { id: 'coffee-machine', name: 'Cafeteira Expresso', w: 0.3, d: 0.35, h: 0.4, by: 0.85, pr: 'base', modelUrl: '/models/kitchenCoffeeMachine.glb', dm: { t: 'metal', c: '#e11d48' } },
      { id: 'blender', name: 'Liquidificador', w: 0.25, d: 0.25, h: 0.45, by: 0.85, pr: 'base', modelUrl: '/models/kitchenBlender.glb', dm: { t: 'metal', c: '#2563eb' } },
      { id: 'toaster', name: 'Torradeira Elétrica', w: 0.3, d: 0.2, h: 0.22, by: 0.85, pr: 'base', modelUrl: '/models/toaster.glb', dm: { t: 'metal', c: '#e2e8f0' } },
      { id: 'hood-large', name: 'Coifa Ilha Inox Pro', w: 0.9, d: 0.6, h: 0.8, by: 1.8, pr: 'ce', modelUrl: '/models/hoodLarge.glb', dm: { t: 'metal', c: '#d4d4d8' } },
      { id: 'hood-modern', name: 'Depurador Slim de Parede', w: 0.8, d: 0.5, h: 0.4, by: 1.6, pr: 'wall', modelUrl: '/models/hoodModern.glb', dm: { t: 'metal', c: '#18181b' } },
    ],
  },
  {
    id: 'living',
    label: 'Salas & Estar',
    icon: 'Sofa',
    items: [
      { id: 'sofa-design', name: 'Sofá Design 3 Lugares', w: 2.2, d: 0.95, h: 0.85, by: 0, pr: 'up', modelUrl: '/models/loungeDesignSofa.glb', dm: { t: 'fabric', c: '#8C8578' } },
      { id: 'sofa-corner', name: 'Sofá em L de Canto', w: 2.4, d: 2.0, h: 0.85, by: 0, pr: 'up', modelUrl: '/models/loungeDesignSofaCorner.glb', dm: { t: 'fabric', c: '#64748b' } },
      { id: 'sofa-long', name: 'Sofá Modular 4 Lugares', w: 2.6, d: 0.95, h: 0.8, by: 0, pr: 'up', modelUrl: '/models/loungeSofaLong.glb', dm: { t: 'fabric', c: '#334155' } },
      { id: 'sofa-lounge-std', name: 'Sofá Compacto 2 Lugares', w: 1.6, d: 0.85, h: 0.8, by: 0, pr: 'up', modelUrl: '/models/loungeSofa.glb', dm: { t: 'fabric', c: '#a8a29e' } },
      { id: 'sofa-ottoman', name: 'Puff / Ottoman Quadrado', w: 0.8, d: 0.8, h: 0.45, by: 0, pr: 'up', modelUrl: '/models/loungeSofaOttoman.glb', dm: { t: 'fabric', c: '#d4c5a9' } },
      { id: 'chair-armchair', name: 'Poltrona Lounge', w: 0.9, d: 0.85, h: 0.85, by: 0, pr: 'up', modelUrl: '/models/loungeChair.glb', dm: { t: 'leather', c: '#C4853A' } },
      { id: 'chair-relax', name: 'Poltrona Relax Reclinável', w: 0.85, d: 0.9, h: 0.9, by: 0, pr: 'up', modelUrl: '/models/loungeChairRelax.glb', dm: { t: 'fabric', c: '#1e293b' } },
      { id: 'chair-design', name: 'Poltrona Escandinava', w: 0.8, d: 0.75, h: 0.8, by: 0, pr: 'up', modelUrl: '/models/loungeDesignChair.glb', dm: { t: 'fabric', c: '#e2e8f0' } },
      { id: 'tv-modern', name: 'Smart TV 65" Ultra HD', w: 1.45, d: 0.1, h: 0.85, by: 0.7, pr: 'wall', modelUrl: '/models/televisionModern.glb', dm: { t: 'metal', c: '#0f172a' } },
      { id: 'tv-cabinet', name: 'Rack para TV com Painel', w: 1.8, d: 0.45, h: 0.55, by: 0, pr: 'fr', modelUrl: '/models/cabinetTelevision.glb', dm: { t: 'wood', c: '#3b2f2f' } },
      { id: 'tv-cabinet-doors', name: 'Rack TV com Portas e Nichos', w: 1.6, d: 0.45, h: 0.6, by: 0, pr: 'fr', modelUrl: '/models/cabinetTelevisionDoors.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'table-coffee-rect', name: 'Mesa de Centro Carvalho', w: 1.2, d: 0.6, h: 0.4, by: 0, pr: 'fr', modelUrl: '/models/tableCoffee.glb', dm: { t: 'wood', c: '#C4A67D' } },
      { id: 'table-coffee-glass', name: 'Mesa de Centro Tampo Vidro', w: 1.1, d: 0.6, h: 0.4, by: 0, pr: 'fr', modelUrl: '/models/tableCoffeeGlass.glb', dm: { t: 'ceramic', c: '#ffffff' } },
      { id: 'table-coffee-sq', name: 'Mesa de Centro Quadrada', w: 0.8, d: 0.8, h: 0.4, by: 0, pr: 'fr', modelUrl: '/models/tableCoffeeSquare.glb', dm: { t: 'wood', c: '#2c2c2c' } },
      { id: 'sidetable-std', name: 'Mesa Lateral de Apoio', w: 0.5, d: 0.5, h: 0.55, by: 0, pr: 'fr', modelUrl: '/models/sideTable.glb', dm: { t: 'wood', c: '#d97706' } },
      { id: 'sidetable-drawers', name: 'Mesa Lateral com Gaveta', w: 0.5, d: 0.45, h: 0.55, by: 0, pr: 'fr', modelUrl: '/models/sideTableDrawers.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'bookcase-open', name: 'Estante Livreiro Aberta', w: 0.9, d: 0.35, h: 1.9, by: 0, pr: 'wall', modelUrl: '/models/bookcaseOpen.glb', dm: { t: 'wood', c: '#5c4033' } },
      { id: 'bookcase-closed', name: 'Estante Livreiro com Portas', w: 0.9, d: 0.38, h: 1.9, by: 0, pr: 'wall', modelUrl: '/models/bookcaseClosedDoors.glb', dm: { t: 'wood', c: '#3a3a3a' } },
      { id: 'bookcase-wide', name: 'Estante Multiuso Larga', w: 1.4, d: 0.35, h: 1.9, by: 0, pr: 'wall', modelUrl: '/models/bookcaseClosedWide.glb', dm: { t: 'wood', c: '#ffffff' } },
    ],
  },
  {
    id: 'bedroom',
    label: 'Quartos & Camas',
    icon: 'Bed',
    items: [
      { id: 'bed-double', name: 'Cama Casal Queen Size', w: 1.6, d: 2.0, h: 0.95, by: 0, pr: 'up', modelUrl: '/models/bedDouble.glb', dm: { t: 'wood', c: '#3b82f6' } },
      { id: 'bed-single', name: 'Cama Solteiro Confort', w: 1.0, d: 1.95, h: 0.85, by: 0, pr: 'up', modelUrl: '/models/bedSingle.glb', dm: { t: 'wood', c: '#60a5fa' } },
      { id: 'bed-bunk', name: 'Beliche Infantil / Juvenil', w: 1.05, d: 2.0, h: 1.7, by: 0, pr: 'up', modelUrl: '/models/bedBunk.glb', dm: { t: 'wood', c: '#818cf8' } },
      { id: 'nightstand-table', name: 'Mesa de Cabeceira', w: 0.5, d: 0.45, h: 0.55, by: 0, pr: 'fr', modelUrl: '/models/cabinetBedDrawerTable.glb', dm: { t: 'wood', c: '#C4A67D' } },
      { id: 'nightstand-drawer', name: 'Gaveteiro de Cabeceira', w: 0.5, d: 0.45, h: 0.6, by: 0, pr: 'fr', modelUrl: '/models/cabinetBedDrawer.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'bedroom-cabinet', name: 'Cômoda 4 Gavetas', w: 0.9, d: 0.5, h: 0.85, by: 0, pr: 'fr', modelUrl: '/models/cabinetBed.glb', dm: { t: 'wood', c: '#3a3a3a' } },
      { id: 'wardrobe-doors', name: 'Guarda-Roupa 2 Portas', w: 1.2, d: 0.6, h: 2.1, by: 0, pr: 'wall', modelUrl: '/models/bookcaseClosedDoors.glb', dm: { t: 'wood', c: '#5c4033' } },
      { id: 'wardrobe-wide', name: 'Guarda-Roupa Casal Amplo', w: 1.8, d: 0.6, h: 2.1, by: 0, pr: 'wall', modelUrl: '/models/bookcaseClosedWide.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'pillow-std', name: 'Almofada Decorativa', w: 0.45, d: 0.45, h: 0.18, by: 0.5, pr: 'up', modelUrl: '/models/pillow.glb', dm: { t: 'fabric', c: '#f59e0b' } },
      { id: 'pillow-long', name: 'Almofada Retangular Longa', w: 0.7, d: 0.35, h: 0.18, by: 0.5, pr: 'up', modelUrl: '/models/pillowLong.glb', dm: { t: 'fabric', c: '#3b82f6' } },
      { id: 'bench-cushion', name: 'Recamier / Banco Peseira', w: 1.2, d: 0.45, h: 0.48, by: 0, pr: 'up', modelUrl: '/models/benchCushion.glb', dm: { t: 'fabric', c: '#e2e8f0' } },
    ],
  },
  {
    id: 'bathroom',
    label: 'Banheiros & Lavanderia',
    icon: 'Bath',
    items: [
      { id: 'bath-cabinet', name: 'Gabinete para Pia Banheiro', w: 0.8, d: 0.5, h: 0.82, by: 0, pr: 'base', modelUrl: '/models/bathroomCabinet.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'bath-cabinet-drawer', name: 'Gabinete Banheiro com Gaveta', w: 0.8, d: 0.5, h: 0.82, by: 0, pr: 'base', modelUrl: '/models/bathroomCabinetDrawer.glb', dm: { t: 'wood', c: '#334155' } },
      { id: 'bath-sink-oval', name: 'Cuba / Pia Suspensa Oval', w: 0.6, d: 0.45, h: 0.85, by: 0, pr: 'wall', modelUrl: '/models/bathroomSink.glb', dm: { t: 'ceramic', c: '#ffffff' } },
      { id: 'bath-sink-sq', name: 'Cuba Quadrada de Apoio', w: 0.5, d: 0.45, h: 0.85, by: 0, pr: 'wall', modelUrl: '/models/bathroomSinkSquare.glb', dm: { t: 'ceramic', c: '#ffffff' } },
      { id: 'toilet-std', name: 'Vaso Sanitário com Caixa', w: 0.42, d: 0.68, h: 0.78, by: 0, pr: 'fr', modelUrl: '/models/toilet.glb', dm: { t: 'ceramic', c: '#ffffff' } },
      { id: 'toilet-square', name: 'Vaso Sanitário Moderno', w: 0.42, d: 0.65, h: 0.78, by: 0, pr: 'fr', modelUrl: '/models/toiletSquare.glb', dm: { t: 'ceramic', c: '#ffffff' } },
      { id: 'bathtub-lux', name: 'Banheira de Imersão Oval', w: 1.7, d: 0.8, h: 0.6, by: 0, pr: 'fr', modelUrl: '/models/bathtub.glb', dm: { t: 'ceramic', c: '#ffffff' } },
      { id: 'shower-box', name: 'Box de Banheiro Retangular', w: 1.0, d: 1.0, h: 2.1, by: 0, pr: 'fr', modelUrl: '/models/shower.glb', dm: { t: 'ceramic', c: '#e2e8f0' } },
      { id: 'shower-round', name: 'Box de Banheiro Curvo de Canto', w: 1.0, d: 1.0, h: 2.1, by: 0, pr: 'fr', modelUrl: '/models/showerRound.glb', dm: { t: 'ceramic', c: '#e2e8f0' } },
      { id: 'bath-mirror', name: 'Espelho de Parede com Moldura', w: 0.6, d: 0.05, h: 0.8, by: 1.2, pr: 'wall', modelUrl: '/models/bathroomMirror.glb', dm: { t: 'metal', c: '#2c2c2c' } },
      { id: 'washer-front', name: 'Máquina de Lavar Roupas', w: 0.65, d: 0.65, h: 0.88, by: 0, pr: 'fr', modelUrl: '/models/washer.glb', dm: { t: 'metal', c: '#ffffff' } },
      { id: 'dryer-std', name: 'Secadora de Roupas', w: 0.65, d: 0.65, h: 0.88, by: 0, pr: 'fr', modelUrl: '/models/dryer.glb', dm: { t: 'metal', c: '#e4e4e7' } },
      { id: 'washer-dryer-stack', name: 'Torre de Lavagem (Lava & Seca)', w: 0.65, d: 0.68, h: 1.85, by: 0, pr: 'fr', modelUrl: '/models/washerDryerStacked.glb', dm: { t: 'metal', c: '#d4d4d8' } },
    ],
  },
  {
    id: 'dining',
    label: 'Mesas & Jantar',
    icon: 'Utensils',
    items: [
      { id: 'table-cross', name: 'Mesa de Jantar Madeira Maciça', w: 1.8, d: 0.9, h: 0.76, by: 0, pr: 'fr', modelUrl: '/models/tableCross.glb', dm: { t: 'wood', c: '#5C4033' } },
      { id: 'table-cross-cloth', name: 'Mesa de Jantar com Toalha', w: 1.8, d: 0.9, h: 0.76, by: 0, pr: 'fr', modelUrl: '/models/tableCrossCloth.glb', dm: { t: 'fabric', c: '#f8fafc' } },
      { id: 'table-dining-std', name: 'Mesa Retangular 6 Lugares', w: 1.6, d: 0.85, h: 0.76, by: 0, pr: 'fr', modelUrl: '/models/table.glb', dm: { t: 'wood', c: '#C4A67D' } },
      { id: 'table-glass', name: 'Mesa com Tampo de Vidro', w: 1.6, d: 0.9, h: 0.76, by: 0, pr: 'fr', modelUrl: '/models/tableGlass.glb', dm: { t: 'ceramic', c: '#ffffff' } },
      { id: 'table-round', name: 'Mesa Redonda 4 Lugares', w: 1.2, d: 1.2, h: 0.76, by: 0, pr: 'fr', modelUrl: '/models/tableRound.glb', dm: { t: 'wood', c: '#3a3a3a' } },
      { id: 'chair-wood', name: 'Cadeira de Madeira Estilizada', w: 0.48, d: 0.5, h: 0.88, by: 0, pr: 'up', modelUrl: '/models/chair.glb', dm: { t: 'wood', c: '#5c4033' } },
      { id: 'chair-cushion', name: 'Cadeira Estofada Jantar', w: 0.5, d: 0.52, h: 0.9, by: 0, pr: 'up', modelUrl: '/models/chairCushion.glb', dm: { t: 'fabric', c: '#D4C5A9' } },
      { id: 'chair-modern-cushion', name: 'Cadeira Moderna Acolchoada', w: 0.5, d: 0.5, h: 0.86, by: 0, pr: 'up', modelUrl: '/models/chairModernCushion.glb', dm: { t: 'fabric', c: '#2A9D8F' } },
      { id: 'chair-rounded', name: 'Cadeira Anatômica Curva', w: 0.52, d: 0.52, h: 0.82, by: 0, pr: 'up', modelUrl: '/models/chairRounded.glb', dm: { t: 'wood', c: '#C4A67D' } },
      { id: 'stool-bar', name: 'Banqueta Alta para Ilha/Bar', w: 0.42, d: 0.42, h: 0.95, by: 0, pr: 'up', modelUrl: '/models/stoolBar.glb', dm: { t: 'metal', c: '#2C2C2C' } },
      { id: 'stool-bar-sq', name: 'Banqueta Bar Quadrada', w: 0.4, d: 0.4, h: 0.95, by: 0, pr: 'up', modelUrl: '/models/stoolBarSquare.glb', dm: { t: 'wood', c: '#d97706' } },
      { id: 'bench-std', name: 'Banco Longo de Madeira', w: 1.4, d: 0.4, h: 0.48, by: 0, pr: 'fr', modelUrl: '/models/bench.glb', dm: { t: 'wood', c: '#5c4033' } },
    ],
  },
  {
    id: 'office',
    label: 'Escritório & Home Office',
    icon: 'Briefcase',
    items: [
      { id: 'desk-std', name: 'Mesa Escrivaninha Pro', w: 1.4, d: 0.7, h: 0.75, by: 0, pr: 'fr', modelUrl: '/models/desk.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'desk-corner', name: 'Mesa de Escritório em L', w: 1.6, d: 1.4, h: 0.75, by: 0, pr: 'fr', modelUrl: '/models/deskCorner.glb', dm: { t: 'wood', c: '#2c2c2c' } },
      { id: 'chair-desk-ergo', name: 'Cadeira Gamer / Presidente Ergo', w: 0.65, d: 0.65, h: 1.15, by: 0, pr: 'up', modelUrl: '/models/chairDesk.glb', dm: { t: 'leather', c: '#2563eb' } },
      { id: 'chair-office-modern', name: 'Cadeira Office Minimalista', w: 0.55, d: 0.55, h: 0.9, by: 0, pr: 'up', modelUrl: '/models/chairModernFrameCushion.glb', dm: { t: 'fabric', c: '#475569' } },
      { id: 'computer-monitor', name: 'Monitor Ultrawide 34"', w: 0.8, d: 0.2, h: 0.48, by: 0.75, pr: 'base', modelUrl: '/models/computerScreen.glb', dm: { t: 'metal', c: '#0f172a' } },
      { id: 'computer-keyboard', name: 'Teclado Mecânico RGB', w: 0.45, d: 0.15, h: 0.04, by: 0.75, pr: 'base', modelUrl: '/models/computerKeyboard.glb', dm: { t: 'metal', c: '#18181b' } },
      { id: 'computer-mouse', name: 'Mouse Óptico Gamer', w: 0.08, d: 0.12, h: 0.04, by: 0.75, pr: 'base', modelUrl: '/models/computerMouse.glb', dm: { t: 'metal', c: '#18181b' } },
      { id: 'laptop-pro', name: 'Notebook / Laptop Pro', w: 0.36, d: 0.25, h: 0.2, by: 0.75, pr: 'base', modelUrl: '/models/laptop.glb', dm: { t: 'metal', c: '#94a3b8' } },
      { id: 'bookcase-low', name: 'Gaveteiro / Livreiro Baixo', w: 0.8, d: 0.35, h: 0.9, by: 0, pr: 'fr', modelUrl: '/models/bookcaseOpenLow.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'books-stack', name: 'Livros Empilhados', w: 0.25, d: 0.2, h: 0.15, by: 0.75, pr: 'base', modelUrl: '/models/books.glb', dm: { t: 'fabric', c: '#ef4444' } },
    ],
  },
  {
    id: 'decor',
    label: 'Iluminação & Decoração',
    icon: 'Sparkles',
    items: [
      { id: 'lamp-floor-round', name: 'Luminária de Chão Retrô', w: 0.45, d: 0.45, h: 1.6, by: 0, pr: 'mt', modelUrl: '/models/lampRoundFloor.glb', dm: { t: 'metal', c: '#eab308' } },
      { id: 'lamp-floor-sq', name: 'Luminária de Coluna Moderna', w: 0.4, d: 0.4, h: 1.65, by: 0, pr: 'mt', modelUrl: '/models/lampSquareFloor.glb', dm: { t: 'metal', c: '#2c2c2c' } },
      { id: 'lamp-table-round', name: 'Abajur Redondo de Mesa', w: 0.3, d: 0.3, h: 0.45, by: 0.55, pr: 'base', modelUrl: '/models/lampRoundTable.glb', dm: { t: 'ceramic', c: '#fde68a' } },
      { id: 'lamp-table-sq', name: 'Abajur Quadrado de Mesa', w: 0.28, d: 0.28, h: 0.45, by: 0.55, pr: 'base', modelUrl: '/models/lampSquareTable.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'lamp-ceiling-sq', name: 'Plafon / Lustre de Teto', w: 0.5, d: 0.5, h: 0.15, by: 2.5, pr: 'ce', modelUrl: '/models/lampSquareCeiling.glb', dm: { t: 'metal', c: '#ffffff' } },
      { id: 'lamp-wall-sconce', name: 'Arandela de Parede', w: 0.2, d: 0.15, h: 0.25, by: 1.8, pr: 'wall', modelUrl: '/models/lampWall.glb', dm: { t: 'metal', c: '#d97706' } },
      { id: 'ceiling-fan', name: 'Ventilador de Teto com Luz', w: 1.1, d: 1.1, h: 0.4, by: 2.3, pr: 'ce', modelUrl: '/models/ceilingFan.glb', dm: { t: 'metal', c: '#ffffff' } },
      { id: 'plant-potted', name: 'Vaso com Planta Tropical', w: 0.5, d: 0.5, h: 0.85, by: 0, pr: 'mt', modelUrl: '/models/pottedPlant.glb', dm: { t: 'ceramic', c: '#22c55e' } },
      { id: 'plant-small-1', name: 'Vaso de Folhagem Decorativa', w: 0.35, d: 0.35, h: 0.5, by: 0, pr: 'base', modelUrl: '/models/plantSmall1.glb', dm: { t: 'ceramic', c: '#16a34a' } },
      { id: 'plant-small-2', name: 'Mini Samambaia de Mesa', w: 0.3, d: 0.3, h: 0.4, by: 0.5, pr: 'base', modelUrl: '/models/plantSmall2.glb', dm: { t: 'ceramic', c: '#4ade80' } },
      { id: 'plant-small-3', name: 'Suculenta / Cacto Pote', w: 0.25, d: 0.25, h: 0.35, by: 0.75, pr: 'base', modelUrl: '/models/plantSmall3.glb', dm: { t: 'ceramic', c: '#15803d' } },
      { id: 'rug-rect', name: 'Tapete Retangular 2x3m', w: 3.0, d: 2.0, h: 0.015, by: 0.005, pr: 'up', modelUrl: '/models/rugRectangle.glb', dm: { t: 'fabric', c: '#64748b' } },
      { id: 'rug-round', name: 'Tapete Redondo 2m', w: 2.0, d: 2.0, h: 0.015, by: 0.005, pr: 'up', modelUrl: '/models/rugRound.glb', dm: { t: 'fabric', c: '#d4c5a9' } },
      { id: 'rug-sq', name: 'Tapete Quadrado 2x2m', w: 2.0, d: 2.0, h: 0.015, by: 0.005, pr: 'up', modelUrl: '/models/rugSquare.glb', dm: { t: 'fabric', c: '#a8a29e' } },
      { id: 'rug-doormat', name: 'Capacho de Entrada', w: 0.7, d: 0.45, h: 0.01, by: 0.005, pr: 'up', modelUrl: '/models/rugDoormat.glb', dm: { t: 'fabric', c: '#92400e' } },
      { id: 'speaker-tower', name: 'Caixa de Som Torre Hi-Fi', w: 0.3, d: 0.3, h: 0.9, by: 0, pr: 'mt', modelUrl: '/models/speaker.glb', dm: { t: 'metal', c: '#18181b' } },
      { id: 'speaker-small', name: 'Smart Speaker Bluetooth', w: 0.15, d: 0.15, h: 0.2, by: 0.75, pr: 'base', modelUrl: '/models/speakerSmall.glb', dm: { t: 'metal', c: '#3b82f6' } },
      { id: 'radio-vintage', name: 'Rádio Retrô Vintage', w: 0.35, d: 0.18, h: 0.22, by: 0.75, pr: 'base', modelUrl: '/models/radio.glb', dm: { t: 'wood', c: '#92400e' } },
      { id: 'coat-rack', name: 'Cabideiro Mancebo de Piso', w: 0.4, d: 0.4, h: 1.75, by: 0, pr: 'mt', modelUrl: '/models/coatRackStanding.glb', dm: { t: 'wood', c: '#5c4033' } },
      { id: 'trashcan-office', name: 'Lixeira Inox com Pedal', w: 0.3, d: 0.3, h: 0.45, by: 0, pr: 'mt', modelUrl: '/models/trashcan.glb', dm: { t: 'metal', c: '#d4d4d8' } },
    ],
  },
  {
    id: 'outdoor',
    label: 'Área Externa & Jardim',
    icon: 'Trees',
    items: [
      { id: 'tree-oak', name: 'Carvalho / Árvore Grande', w: 2.8, d: 2.8, h: 4.5, by: 0, pr: 'mt', modelUrl: '/models/outdoor_tree_oak.glb', dm: { t: 'wood', c: '#166534' } },
      { id: 'tree-default', name: 'Árvore Copa Verde', w: 2.4, d: 2.4, h: 4.0, by: 0, pr: 'mt', modelUrl: '/models/outdoor_tree_default.glb', dm: { t: 'wood', c: '#15803d' } },
      { id: 'tree-detailed', name: 'Árvore Detalhada', w: 2.5, d: 2.5, h: 4.2, by: 0, pr: 'mt', modelUrl: '/models/outdoor_tree_detailed.glb', dm: { t: 'wood', c: '#14532d' } },
      { id: 'tree-palm', name: 'Palmeira Tropical', w: 2.0, d: 2.0, h: 4.5, by: 0, pr: 'mt', modelUrl: '/models/outdoor_tree_palm.glb', dm: { t: 'wood', c: '#16a34a' } },
      { id: 'tree-pine', name: 'Pinheiro / Conífera', w: 1.6, d: 1.6, h: 4.2, by: 0, pr: 'mt', modelUrl: '/models/outdoor_tree_pineRoundA.glb', dm: { t: 'wood', c: '#065f46' } },
      { id: 'plant-bush', name: 'Arbusto de Jardim Redondo', w: 0.9, d: 0.9, h: 0.8, by: 0, pr: 'mt', modelUrl: '/models/outdoor_plant_bush.glb', dm: { t: 'fabric', c: '#22c55e' } },
      { id: 'plant-bush-detailed', name: 'Arbusto Folhagem Densa', w: 1.1, d: 1.1, h: 0.95, by: 0, pr: 'mt', modelUrl: '/models/outdoor_plant_bushDetailed.glb', dm: { t: 'fabric', c: '#16a34a' } },
      { id: 'cactus-tall', name: 'Cacto Mandacaru Alto', w: 0.6, d: 0.6, h: 1.8, by: 0, pr: 'mt', modelUrl: '/models/outdoor_cactus_tall.glb', dm: { t: 'fabric', c: '#15803d' } },
      { id: 'flower-purple', name: 'Canteiro Flores Roxas', w: 0.6, d: 0.6, h: 0.45, by: 0, pr: 'mt', modelUrl: '/models/outdoor_flower_purpleA.glb', dm: { t: 'fabric', c: '#a855f7' } },
      { id: 'flower-red', name: 'Canteiro Flores Vermelhas', w: 0.6, d: 0.6, h: 0.45, by: 0, pr: 'mt', modelUrl: '/models/outdoor_flower_redA.glb', dm: { t: 'fabric', c: '#ef4444' } },
      { id: 'flower-yellow', name: 'Canteiro Flores Amarelas', w: 0.6, d: 0.6, h: 0.45, by: 0, pr: 'mt', modelUrl: '/models/outdoor_flower_yellowA.glb', dm: { t: 'fabric', c: '#eab308' } },
      { id: 'campfire-stones', name: 'Lareira Externa com Pedras (Fire Pit)', w: 1.0, d: 1.0, h: 0.4, by: 0, pr: 'fr', modelUrl: '/models/outdoor_campfire_stones.glb', dm: { t: 'metal', c: '#f97316' } },
      { id: 'tent-camping', name: 'Tenda / Barraca Camping', w: 2.2, d: 2.0, h: 1.4, by: 0, pr: 'mt', modelUrl: '/models/outdoor_tent_detailedOpen.glb', dm: { t: 'fabric', c: '#d97706' } },
      { id: 'pot-large', name: 'Vaso Cerâmico de Jardim Grande', w: 0.6, d: 0.6, h: 0.7, by: 0, pr: 'mt', modelUrl: '/models/outdoor_pot_large.glb', dm: { t: 'ceramic', c: '#c2410c' } },
      { id: 'rock-large', name: 'Pedra Ornamental Paisagismo', w: 1.2, d: 0.9, h: 0.65, by: 0, pr: 'mt', modelUrl: '/models/outdoor_rock_largeA.glb', dm: { t: 'ceramic', c: '#78716c' } },
    ],
  },
  {
    id: 'structure',
    label: 'Estruturas & Divisórias',
    icon: 'Fence',
    items: [
      { id: 'fence-planks', name: 'Cerca de Madeira 2m', w: 2.0, d: 0.12, h: 1.0, by: 0, pr: 'mt', modelUrl: '/models/outdoor_fence_planks.glb', dm: { t: 'wood', c: '#a16207' } },
      { id: 'fence-gate', name: 'Portão de Cerca com Trinco', w: 1.0, d: 0.12, h: 1.0, by: 0, pr: 'mt', modelUrl: '/models/outdoor_fence_gate.glb', dm: { t: 'wood', c: '#a16207' } },
      { id: 'fence-simple', name: 'Grade de Proteção', w: 2.0, d: 0.1, h: 0.9, by: 0, pr: 'mt', modelUrl: '/models/outdoor_fence_simple.glb', dm: { t: 'metal', c: '#ffffff' } },
      { id: 'stairs-straight', name: 'Escada Reta com Degraus', w: 1.0, d: 2.4, h: 2.6, by: 0, pr: 'mt', modelUrl: '/models/stairs.glb', dm: { t: 'wood', c: '#5c4033' } },
      { id: 'stairs-corner', name: 'Escada com Patamar em L', w: 2.0, d: 2.0, h: 2.6, by: 0, pr: 'mt', modelUrl: '/models/stairsCorner.glb', dm: { t: 'wood', c: '#5c4033' } },
      { id: 'doorway-std', name: 'Vão de Porta com Batente', w: 0.9, d: 0.15, h: 2.1, by: 0, pr: 'wall', modelUrl: '/models/doorwayFront.glb', dm: { t: 'wood', c: '#ffffff' } },
      { id: 'wall-window-slide', name: 'Janela de Vidro de Correr', w: 1.4, d: 0.15, h: 1.2, by: 1.0, pr: 'wall', modelUrl: '/models/wallWindowSlide.glb', dm: { t: 'metal', c: '#e2e8f0' } },
    ],
  },
];

export const MATERIAL_OPTIONS: Record<MaterialType, { n: string; c: string }[]> = {
  fabric: [
    { n: 'Linho Bege', c: '#D4C5A9' },
    { n: 'Veludo Teal', c: '#2A9D8F' },
    { n: 'Algodão Cinza', c: '#8C8578' },
    { n: 'Azul Petróleo', c: '#1d3557' },
    { n: 'Terracota', c: '#c2410c' },
    { n: 'Verde Oliva', c: '#3f6212' },
  ],
  leather: [
    { n: 'Couro Caramelo (Tan)', c: '#C4853A' },
    { n: 'Couro Preto', c: '#2C2C2C' },
    { n: 'Couro Café', c: '#4a2c11' },
    { n: 'Couro Off-White', c: '#e4e4e7' },
  ],
  wood: [
    { n: 'Branco Acetinado', c: '#FFFFFF' },
    { n: 'Carvalho Natural', c: '#C4A67D' },
    { n: 'Nogueira Escura', c: '#5C4033' },
    { n: 'Grafite / Chumbo', c: '#3A3A3A' },
    { n: 'Freijó Dourado', c: '#b45309' },
    { n: 'Preto Ébano', c: '#18181b' },
  ],
  metal: [
    { n: 'Inox Escovado', c: '#E0E0E0' },
    { n: 'Preto Fosco (Matte Black)', c: '#2C2C2C' },
    { n: 'Dourado Champanhe', c: '#d4af37' },
    { n: 'Bronze Antigo', c: '#78350f' },
    { n: 'Cobre Rosé', c: '#b45309' },
  ],
  ceramic: [
    { n: 'Branco Glazed', c: '#FFFFFF' },
    { n: 'Mármore Calacatta', c: '#F0F0F0' },
    { n: 'Mármore Nero Marquina', c: '#1c1917' },
    { n: 'Cimento Queimado', c: '#78716c' },
  ],
  gltf: [],
};
